### ISSUE TITLE
Add tests for ElasticSearch querying functions

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#10]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, there are no tests in the library. There are many edge cases where the library might fail. So, we need to add tests to cover all the edge cases and change the code accordingly.

**Expected behavior:**

Unit tests for all the library functions dealing with ES queries should be there.

**Other information:**

The task here is to check if the constructed ES query by any functions matches the expected query based on the given parameters.

**Comment by epicadk** [comment]
Can you provide some links that would help with this?
