### ISSUE TITLE
Revamping README

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#11]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, there is -
- No proper project description in `README` file.
- ~No project's title image~
- No badges (eg. code coverage, latest library version, Gitter channel, etc.)
- No Table of Contents
- No separate `Docs` section with instructions on how to build modified docs

**Expected behavior:**

All the above-described things should be there in the `README` file.

**Other information:**

Refer to my project - https://github.com/appbaseio/appbase-swift

**Comment by abhinav12k** [comment]
Can i work on this issue?

**Comment by harsh-2711** [comment]
Yes. Assigning it to you.
