### ISSUE TITLE
Replace hardcoded string with resource variables

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#13]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

All the textual content and the colors are hardcoded everywhere.

**Expected behavior:**

This should be placed inside `res` folder and should be referenced accordingly to support localization.

**Other information:**

**Comment by adit19shah** [comment]
I am interested in contributing this feature. Should I start working on it ?

**Comment by harsh-2711** [comment]
Yes please. I'll assign it to you.
