### ISSUE TITLE
Migrate models to Kotlin

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#14]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

All the models are written in Java and hence need getters and setters which increases verbosity.

**Expected behavior:**

Migrate Java classes to Kotlin data classes to remove verbosity.

**Other information:**

**Comment by adit19shah** [comment]
Can I work on this issue ?

**Comment by harsh-2711** [comment]
@adit19shah Issue is solved now. Please take up other issues.

**Comment by adit19shah** [comment]
Okay, no problem.
