### ISSUE TITLE
Add "How to" guide for ES

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#15]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

There is no documentation linked with the project which explains - 
- how to host an ES cluster
- how to ingest data on ES nodes
- how to use this library to connect to ES cluster for fetching search results on ingested data

**Expected behavior:**

Add a good guide covering the above points in the `Wiki` section

**Other information:**

**Comment by epicadk** [comment]
Can you provide some links that would help with this?
