### ISSUE TITLE
Feature: Add Kotlin Usage

### ISSUE THREAD

**Issue by epicadk** [harsh-2711/appbase-search-widget#20]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

No Kotlin Demo
**Expected behavior:**

Should have kotlin demo

**Comment by harsh-2711** [comment]
@epicadk We don't need to add the same functionality with Kotlin again. We can rather modify the Java files and try to convert them to Kotlin as much as we can. Showing the same functionality in Kotlin won't make any difference on screen for the user.
