### ISSUE TITLE
DefaultClientSuggestions adapter cleared multiple times

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#24]
**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

`DefaultClientSuggestions` adapter is cleared multiple times when any of the navigation buttons are clicked. For reference - https://github.com/harsh-2711/android-search-ui/blob/69a10a8105b951f9342aba7035a6d11fc91bb896/searchwidget/src/main/java/com/harsh/searchwidget/SearchBar.java#L1109 and https://github.com/harsh-2711/android-search-ui/blob/69a10a8105b951f9342aba7035a6d11fc91bb896/searchwidget/src/main/java/com/harsh/searchwidget/SearchBar.java#L1122 

**Expected behavior:**

The adapter should be cleared and set only once.

**Other information:**

**Comment by adit19shah** [comment]
Can I work on this issue ?

**Comment by harsh-2711** [comment]
Sure. Assigning it to you.
