### ISSUE TITLE
Remove raw use of parametrized classes

### ISSUE THREAD

**Issue by harsh-2711** [harsh-2711/appbase-search-widget#9]
**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

There are many declarations in the project where `Parametrized Classes` are used directly (raw use). This might cause a class error in the project using this library.

**Expected behavior:**

Raw use of `Parametrized Classes` shouldn't be there

**Other information:**

https://stackoverflow.com/questions/24672749/raw-use-of-parameterized-class this might help

**Comment by epicadk** [comment]
Can I work on this?

**Comment by harsh-2711** [comment]
Yes. I'll assign it to you.
